### ISSUE TITLE
Uber Console doesnt show compiler errors

### ISSUE THREAD

**Issue by michidk** [bbbscarter/UberLogger#19] opened 2017-03-04 17:44 UTC
Uber Console doesnt show compiler errors.
If I want to see the compiler errors, I have to switch to the old Unity console.

Can this be fixed?

**Comment by Kalmalyzer** [comment] 2017-03-08 16:04
Hi,

under which conditions does this happen? Can you provide some screenshots?

Here is what it looks like if I trigger a recompile (which results in a couple of warning messages) in one of my projects. You can see some Unity error messages (because the game was running) and also a bunch of warning messages:

![image](https://cloud.githubusercontent.com/assets/1208699/23711767/1a9f44bc-0421-11e7-97fd-3549ac372e6e.png)

And here is an example of a compile error -- I put "blah" at the top of a source file:

![image](https://cloud.githubusercontent.com/assets/1208699/23711836/540b0d12-0421-11e7-9f33-a08e63c6f7a3.png)

**Comment by michidk** [comment] 2017-03-12 14:52
I guess this was some kind of edge case. Can't reproduce it myself. Gonna report back if it happens again.

**Comment by michidk** [comment] 2017-03-12 15:06
I just reproduced it. Here a the steps:
- Have a working project with UberConsole in it.
- Create a new script, and put some compile errors in there (e.g. callinc a not existing method Unity.thisdoesnotexist();)
- Save
- Wait
- Look at the Uber Console.. no error. look at the Unity console: compiler error.

![Screenshot](https://cloud.githubusercontent.com/assets/3979930/23832871/bf6b1b32-073d-11e7-8d3b-517a1144529e.png)

I used the newest source available right now (just updated the submodule) and Unity 5.5.0f3.

**Comment by Kalmalyzer** [comment] 2017-04-09 13:07
Sorry, but I am not able to reproduce this when following your instructions. The error message shows in both Console and Uber Console window for me. I'm using Visual Studio 2015 for editing the code and Unity 5.5.0f3 when testing. Both applications are maximized; I alt-tab between them. Could be that UberConsole was in a bad state due to something else that happened prior to this.

**Comment by bbbscarter** [comment] 2018-01-28 17:02
I've not been able to repro this either. Closing for now, until we can get some fresh repro steps. 

Thanks for reporting @michidk !

**Comment by bbbscarter** [comment] 2018-01-28 17:03
I've not been able to repro this either. Closing for now, until we can get some fresh repro steps.

Thanks for reporting @michidk !

**Closed as completed** 2018-01-28 17:02 UTC
